version: "3.3"
services:
  mongo:
    container_name: 'mongo'
    image: mongo
    restart: always
    volumes:
      - ./data/mongodb:/data/db
  kanception-api:
    container_name: 'kanception-api'
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "4444:4000"
    volumes:
      - type: "bind"
        source: ./api
        target: /home/ubuntu/api
      - /home/ubuntu/api/node_modules/
    depends_on:
      - mongo
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanception-api.rule=Host(`api.kanception.io`)"
      - "traefik.http.routers.kanception-api.entrypoints=web"
  kanception:
    container_name: 'kanception'
    build:
      context: ./kanception
      dockerfile: Dockerfile.prod
    stdin_open: true
    restart: always
    depends_on:
      - kanception-api
    volumes:
      - type: "bind"
        source: ./kanception
        target: /home/ubuntu/kanception
      - /home/ubuntu/kanception/node_modules/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanception.rule=Host(`app.kanception.io`)"
      - "traefik.http.routers.kanception.entrypoints=web"
      - "traefik.http.services.kanception.loadbalancer.server.port=80"

  traefik:
    image: "traefik:latest"
    restart: always
    command:
        #- "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./data/letsencrypt:/etc/letsencrypt
      - ./cache/ecom_cache:/var/www/ecom_cache
    ports:
     - "80:80"
     - "443:443"


