FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y npm nodejs

RUN npm install -g typescript
RUN groupadd -r ubuntu && useradd -r -g ubuntu ubuntu && \
    mkdir /home/ubuntu && chown ubuntu:ubuntu /home/ubuntu

USER ubuntu
RUN mkdir -p /home/ubuntu/api
WORKDIR /home/ubuntu/api
COPY package*.json ./
RUN npm install
RUN npm link typescript
COPY --chown=ubuntu:ubuntu . /home/ubuntu/api
RUN npm run build


CMD ["npm", "run", "start"]
